apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: map-api-ingress
  namespace: map
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /otusapp($|/)(.*)
        pathType: Prefix
        backend:
          service:
            name: map-api-service
            port:
              number: 8000